updating mainflux to 0.13.0
ns1labs/orb-helm pull request #26
Opened 2022-06-09 17:17 UTC by fhaze

- Added **Keto** dependency
- Update **Makefile** to also load local `ns1labs/*` images into **Kind**

2022-06-21 23:11 UTC, etaques requested changes
Small changes to permit us point to external databases.

2022-06-21 23:11 UTC, etaques commented on charts/orb/values.yaml
> +          name: members
I suppose that is missing here the field to hold the dbhost for keto, to permit us to point to external db such as RDS auth.

2022-06-22 14:25 UTC, fhaze commented
I undestand your point @etaques. I added db host hints on the `values.yml` file to make it easier to undestand.

2022-06-22 15:47 UTC, etaques approved these changes
LGTM
Well done!

2022-06-22 16:21 UTC, weyrick approved these changes

2022-06-24 14:19 UTC, merged